### ISSUE TITLE
Question: Is it okay to include OSQP in a list of Mathematical Programming modules available in Go?

### ISSUE THREAD

**Issue by kwesiRutledge** [jerensl/osqp.go#6]
Hello Jerens!

Thank you for taking the time to develop this interesting module! I am part of the [MatProGo-dev](https://github.com/MatProGo-dev) team and we recently included a link to this in our organization's [README](https://github.com/MatProGo-dev). My question for you is: Is our description of OSQP's capabilities match what this library can do?

Thank you for your time! We hope to include a formal wrapper to osqp.go in the future and may return to ask more questions when that happens.

Best,
Kwesi

**Comment by jerensl** [comment]
Hi Kwesi,

Thank you for reaching out, I appreciate your comment. The purpose of this project is to make a wrapper for the OSQP Interface built from C, to serve an MPC Controller which uses Quadratic Programming as the main goal.

From now on, the MPC example has not working yet, because of the challenge of implementing a sparse Matrix and its own independent calculation, now I'm using gonum for doing the calculations and later parsing the vector-matrix into a sparse matrix

Thank you,
Jerens

**Comment by kwesiRutledge** [comment]
Thanks for the response, Jerens!

My apologies for not responding sooner. By "the MPC example has not working yet" do you mean that [this example](https://github.com/jerensl/osqp.go/blob/main/examples/mpc/main.go) is not working? I may be able to help.

I'm also curious about what you mean by this "the challenge of implementing a sparse Matrix and its own independent calculation". [MatProInterface.go](https://github.com/MatProGo-dev/MatProInterface.go) was built to simplify how to do symbolic math in Go for Quadratic programming and might be able to help. You can see an example of how it was used here: [QP1](https://github.com/MatProGo-dev/Gurobi.go/blob/main/examples/matprointerface/qp1.go).

I will close this issue since you have answered my initial question, but if it sounds like MatProInterface.go could be helpful here, then I may try to contribute to your useful library!
